<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageVersion>11.0.1</PackageVersion>
    <AssemblyVersion>11.0.1</AssemblyVersion>
    <FileVersion>11.0.1</FileVersion>
    <Title>Auto-Version by Yamamari</Title>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <RootNamespace>Yamamari.Library.AutoVersion</RootNamespace>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>Resources/yamamari-logo-package.png</PackageIcon>
    <PackageProjectUrl>https://github.com/yamamari-llc/library-autoversion</PackageProjectUrl>
    <RepositoryUrl>https://github.com/yamamari-llc/library-autoversion</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageId>Yamamari.AutoVersion</PackageId>
    <EnableDynamicLoading>True</EnableDynamicLoading>
    <CustomTasksAssembly>$(OutDir)AutoVersion.dll</CustomTasksAssembly>
    <LangVersion>13</LangVersion>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Resources/yamamari-logo-package.png">
      <Pack>True</Pack>
      <PackagePath>Resources/yamamari-logo-package.png</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\README.md">
      <Link>Resources/README.md</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Framework" Version="17.13.9" CopyLocal="false" Publish="false" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.13.9" CopyLocal="false" Publish="false" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <Target Name="RemoveMicrosoftBuildDllsFromOutput" AfterTargets="ResolveReferences">
    <PropertyGroup>
      <NonCopyLocalPackageReferences Condition="'%(PackageReference.CopyLocal)' == 'false'">;@(PackageReference);</NonCopyLocalPackageReferences>
    </PropertyGroup>
    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="$(NonCopyLocalPackageReferences.Contains(';%(ReferenceCopyLocalPaths.NuGetPackageId);'))" />
    </ItemGroup>
  </Target>
  <PropertyGroup>
    <LatestAutoVersionSignature>{
   "Name": "AutoVersion.csproj",
   "Classes": [
      {
         "Name": "Yamamari.Library.AutoVersion.AutoVersion",
         "Methods": {
            "Execute": {
               "MethodName": "Execute",
               "MethodType": "Boolean",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {
            "BuildEngine": {
               "Name": "BuildEngine",
               "Type": "IBuildEngine",
               "IsReadable": true,
               "IsWritable": true
            },
            "BuildEngine2": {
               "Name": "BuildEngine2",
               "Type": "IBuildEngine2",
               "IsReadable": true,
               "IsWritable": false
            },
            "BuildEngine3": {
               "Name": "BuildEngine3",
               "Type": "IBuildEngine3",
               "IsReadable": true,
               "IsWritable": false
            },
            "BuildEngine4": {
               "Name": "BuildEngine4",
               "Type": "IBuildEngine4",
               "IsReadable": true,
               "IsWritable": false
            },
            "BuildEngine5": {
               "Name": "BuildEngine5",
               "Type": "IBuildEngine5",
               "IsReadable": true,
               "IsWritable": false
            },
            "BuildEngine6": {
               "Name": "BuildEngine6",
               "Type": "IBuildEngine6",
               "IsReadable": true,
               "IsWritable": false
            },
            "BuildEngine7": {
               "Name": "BuildEngine7",
               "Type": "IBuildEngine7",
               "IsReadable": true,
               "IsWritable": false
            },
            "BuildEngine8": {
               "Name": "BuildEngine8",
               "Type": "IBuildEngine8",
               "IsReadable": true,
               "IsWritable": false
            },
            "BuildEngine9": {
               "Name": "BuildEngine9",
               "Type": "IBuildEngine9",
               "IsReadable": true,
               "IsWritable": false
            },
            "HostObject": {
               "Name": "HostObject",
               "Type": "ITaskHost",
               "IsReadable": true,
               "IsWritable": true
            },
            "Log": {
               "Name": "Log",
               "Type": "TaskLoggingHelper",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.Version",
         "Methods": {
            "get_Major": {
               "MethodName": "get_Major",
               "MethodType": "Nullable`1",
               "Overrides": [
                  []
               ]
            },
            "get_Minor": {
               "MethodName": "get_Minor",
               "MethodType": "Nullable`1",
               "Overrides": [
                  []
               ]
            },
            "get_Patch": {
               "MethodName": "get_Patch",
               "MethodType": "Nullable`1",
               "Overrides": [
                  []
               ]
            },
            "ToString": {
               "MethodName": "ToString",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            },
            "Increment": {
               "MethodName": "Increment",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "type",
                        "ParameterType": "VersionType",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "GetHashCode": {
               "MethodName": "GetHashCode",
               "MethodType": "Int32",
               "Overrides": [
                  []
               ]
            },
            "Equals": {
               "MethodName": "Equals",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "obj",
                        "ParameterType": "Object",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "op_Implicit": {
               "MethodName": "op_Implicit",
               "MethodType": "String",
               "Overrides": [
                  [
                     {
                        "ParameterName": "version",
                        "ParameterType": "Version",
                        "IsRequired": true
                     }
                  ],
                  [
                     {
                        "ParameterName": "versionString",
                        "ParameterType": "String",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "op_GreaterThan": {
               "MethodName": "op_GreaterThan",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "v1",
                        "ParameterType": "Version",
                        "IsRequired": true
                     },
                     {
                        "ParameterName": "v2",
                        "ParameterType": "Version",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "op_LessThan": {
               "MethodName": "op_LessThan",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "v1",
                        "ParameterType": "Version",
                        "IsRequired": true
                     },
                     {
                        "ParameterName": "v2",
                        "ParameterType": "Version",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "op_Equality": {
               "MethodName": "op_Equality",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "v1",
                        "ParameterType": "Version",
                        "IsRequired": true
                     },
                     {
                        "ParameterName": "v2",
                        "ParameterType": "Version",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "op_Inequality": {
               "MethodName": "op_Inequality",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "v1",
                        "ParameterType": "Version",
                        "IsRequired": true
                     },
                     {
                        "ParameterName": "v2",
                        "ParameterType": "Version",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "Major": {
               "Name": "Major",
               "Type": "Nullable`1",
               "IsReadable": true,
               "IsWritable": false
            },
            "Minor": {
               "Name": "Minor",
               "Type": "Nullable`1",
               "IsReadable": true,
               "IsWritable": false
            },
            "Patch": {
               "Name": "Patch",
               "Type": "Nullable`1",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.VersionType",
         "Methods": {},
         "Properties": {}
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureStructure.Method",
         "Methods": {
            "get_MethodName": {
               "MethodName": "get_MethodName",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            },
            "set_MethodName": {
               "MethodName": "set_MethodName",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "String",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "get_MethodType": {
               "MethodName": "get_MethodType",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            },
            "set_MethodType": {
               "MethodName": "set_MethodType",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "String",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "get_Overrides": {
               "MethodName": "get_Overrides",
               "MethodType": "MethodOverrides",
               "Overrides": [
                  []
               ]
            },
            "set_Overrides": {
               "MethodName": "set_Overrides",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "MethodOverrides",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "MethodName": {
               "Name": "MethodName",
               "Type": "String",
               "IsReadable": true,
               "IsWritable": true
            },
            "MethodType": {
               "Name": "MethodType",
               "Type": "String",
               "IsReadable": true,
               "IsWritable": true
            },
            "Overrides": {
               "Name": "Overrides",
               "Type": "MethodOverrides",
               "IsReadable": true,
               "IsWritable": true
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureStructure.MethodOverride",
         "Methods": {
            "get_MethodSignature": {
               "MethodName": "get_MethodSignature",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {
            "MethodSignature": {
               "Name": "MethodSignature",
               "Type": "String",
               "IsReadable": true,
               "IsWritable": false
            },
            "Capacity": {
               "Name": "Capacity",
               "Type": "Int32",
               "IsReadable": true,
               "IsWritable": true
            },
            "Count": {
               "Name": "Count",
               "Type": "Int32",
               "IsReadable": true,
               "IsWritable": false
            },
            "Item": {
               "Name": "Item",
               "Type": "MethodOverrideInput",
               "IsReadable": true,
               "IsWritable": true
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureStructure.MethodOverrideInput",
         "Methods": {
            "get_ParameterName": {
               "MethodName": "get_ParameterName",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            },
            "set_ParameterName": {
               "MethodName": "set_ParameterName",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "String",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "get_ParameterType": {
               "MethodName": "get_ParameterType",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            },
            "set_ParameterType": {
               "MethodName": "set_ParameterType",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "String",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "get_IsRequired": {
               "MethodName": "get_IsRequired",
               "MethodType": "Boolean",
               "Overrides": [
                  []
               ]
            },
            "set_IsRequired": {
               "MethodName": "set_IsRequired",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "Boolean",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "ParameterName": {
               "Name": "ParameterName",
               "Type": "String",
               "IsReadable": true,
               "IsWritable": true
            },
            "ParameterType": {
               "Name": "ParameterType",
               "Type": "String",
               "IsReadable": true,
               "IsWritable": true
            },
            "IsRequired": {
               "Name": "IsRequired",
               "Type": "Boolean",
               "IsReadable": true,
               "IsWritable": true
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureStructure.MethodOverrides",
         "Methods": {},
         "Properties": {
            "Capacity": {
               "Name": "Capacity",
               "Type": "Int32",
               "IsReadable": true,
               "IsWritable": true
            },
            "Count": {
               "Name": "Count",
               "Type": "Int32",
               "IsReadable": true,
               "IsWritable": false
            },
            "Item": {
               "Name": "Item",
               "Type": "MethodOverride",
               "IsReadable": true,
               "IsWritable": true
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureStructure.Project",
         "Methods": {
            "get_Name": {
               "MethodName": "get_Name",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            },
            "set_Name": {
               "MethodName": "set_Name",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "String",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "get_Classes": {
               "MethodName": "get_Classes",
               "MethodType": "List`1",
               "Overrides": [
                  []
               ]
            },
            "set_Classes": {
               "MethodName": "set_Classes",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "List`1",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "Name": {
               "Name": "Name",
               "Type": "String",
               "IsReadable": true,
               "IsWritable": true
            },
            "Classes": {
               "Name": "Classes",
               "Type": "List`1",
               "IsReadable": true,
               "IsWritable": true
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureStructure.ProjectClass",
         "Methods": {
            "get_Name": {
               "MethodName": "get_Name",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            },
            "set_Name": {
               "MethodName": "set_Name",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "String",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "get_Methods": {
               "MethodName": "get_Methods",
               "MethodType": "Dictionary`2",
               "Overrides": [
                  []
               ]
            },
            "set_Methods": {
               "MethodName": "set_Methods",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "Dictionary`2",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "get_Properties": {
               "MethodName": "get_Properties",
               "MethodType": "Dictionary`2",
               "Overrides": [
                  []
               ]
            },
            "set_Properties": {
               "MethodName": "set_Properties",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "Dictionary`2",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "Name": {
               "Name": "Name",
               "Type": "String",
               "IsReadable": true,
               "IsWritable": true
            },
            "Methods": {
               "Name": "Methods",
               "Type": "Dictionary`2",
               "IsReadable": true,
               "IsWritable": true
            },
            "Properties": {
               "Name": "Properties",
               "Type": "Dictionary`2",
               "IsReadable": true,
               "IsWritable": true
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureStructure.Property",
         "Methods": {
            "get_Name": {
               "MethodName": "get_Name",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            },
            "set_Name": {
               "MethodName": "set_Name",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "String",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "get_Type": {
               "MethodName": "get_Type",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            },
            "set_Type": {
               "MethodName": "set_Type",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "String",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "get_IsReadable": {
               "MethodName": "get_IsReadable",
               "MethodType": "Boolean",
               "Overrides": [
                  []
               ]
            },
            "set_IsReadable": {
               "MethodName": "set_IsReadable",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "Boolean",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "get_IsWritable": {
               "MethodName": "get_IsWritable",
               "MethodType": "Boolean",
               "Overrides": [
                  []
               ]
            },
            "set_IsWritable": {
               "MethodName": "set_IsWritable",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "Boolean",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "Name": {
               "Name": "Name",
               "Type": "String",
               "IsReadable": true,
               "IsWritable": true
            },
            "Type": {
               "Name": "Type",
               "Type": "String",
               "IsReadable": true,
               "IsWritable": true
            },
            "IsReadable": {
               "Name": "IsReadable",
               "Type": "Boolean",
               "IsReadable": true,
               "IsWritable": true
            },
            "IsWritable": {
               "Name": "IsWritable",
               "Type": "Boolean",
               "IsReadable": true,
               "IsWritable": true
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureStructure.Signature",
         "Methods": {},
         "Properties": {
            "Capacity": {
               "Name": "Capacity",
               "Type": "Int32",
               "IsReadable": true,
               "IsWritable": true
            },
            "Count": {
               "Name": "Count",
               "Type": "Int32",
               "IsReadable": true,
               "IsWritable": false
            },
            "Item": {
               "Name": "Item",
               "Type": "Project",
               "IsReadable": true,
               "IsWritable": true
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureStructure.Signatures",
         "Methods": {
            "get_Older": {
               "MethodName": "get_Older",
               "MethodType": "Signature",
               "Overrides": [
                  []
               ]
            },
            "get_Newer": {
               "MethodName": "get_Newer",
               "MethodType": "Signature",
               "Overrides": [
                  []
               ]
            },
            "GetClassesInBoth": {
               "MethodName": "GetClassesInBoth",
               "MethodType": "SignaturesClasses[]",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {
            "Older": {
               "Name": "Older",
               "Type": "Signature",
               "IsReadable": true,
               "IsWritable": false
            },
            "Newer": {
               "Name": "Newer",
               "Type": "Signature",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureStructure.SignaturesClasses",
         "Methods": {
            "get_Older": {
               "MethodName": "get_Older",
               "MethodType": "ProjectClass",
               "Overrides": [
                  []
               ]
            },
            "get_Newer": {
               "MethodName": "get_Newer",
               "MethodType": "ProjectClass",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {
            "Older": {
               "Name": "Older",
               "Type": "ProjectClass",
               "IsReadable": true,
               "IsWritable": false
            },
            "Newer": {
               "Name": "Newer",
               "Type": "ProjectClass",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.CompareSignatures",
         "Methods": {
            "GetChangeType": {
               "MethodName": "GetChangeType",
               "MethodType": "VersionType",
               "Overrides": [
                  [
                     {
                        "ParameterName": "task",
                        "ParameterType": "ITask",
                        "IsRequired": true
                     },
                     {
                        "ParameterName": "oldSignature",
                        "ParameterType": "Signature",
                        "IsRequired": true
                     },
                     {
                        "ParameterName": "newSignature",
                        "ParameterType": "Signature",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.IEvaluateSignatures",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.MethodInputParameterOverrideRemoved",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.MethodOverrideAdded",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.MethodReturnType",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.MethodsContinueToExist",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.ProjectAdded",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.ProjectClassAdded",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.ProjectClassesContinueToExist",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.ProjectsContinueToExist",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.PropertiesContinueToExist",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.PropertyEditabilityEnhanced",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.PropertyEditabilityReduced",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.PropertyReadabilityEnhanced",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.PropertyReadabilityReduced",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      },
      {
         "Name": "Yamamari.Library.AutoVersion.SignatureEvaluation.PropertyType",
         "Methods": {
            "get_EvaluationImpact": {
               "MethodName": "get_EvaluationImpact",
               "MethodType": "VersionType",
               "Overrides": [
                  []
               ]
            },
            "AreDifferencesPresent": {
               "MethodName": "AreDifferencesPresent",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "signatures",
                        "ParameterType": "Signatures",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {
            "EvaluationImpact": {
               "Name": "EvaluationImpact",
               "Type": "VersionType",
               "IsReadable": true,
               "IsWritable": false
            }
         }
      }
   ]
}</LatestAutoVersionSignature>
  </PropertyGroup>
</Project>