<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Yamamari.Library.PluginArchitecture</AssemblyName>
    <RootNamespace>Yamamari.Library.PluginArchitecture</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Yamamari.PluginArchitecture</PackageId>
    <Title>Plug-in Architecture by Yamamari</Title>
    <PackageProjectUrl>https://github.com/yamamari-llc/library-pluginarchitecture</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/yamamari-llc/library-pluginarchitecture/blob/main/LICENSE</PackageLicenseUrl>
    <RepositoryUrl>https://github.com/yamamari-llc/library-pluginarchitecture</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageIcon>Resources\yamamari-logo-pluginarchitecture.png</PackageIcon>
    <PackageVersion>2.0.5</PackageVersion>
    <AssemblyVersion>2.0.5</AssemblyVersion>
    <FileVersion>2.0.5</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\yamamari-logo-pluginarchitecture.png" />
    <EmbeddedResource Include="Resources\yamamari-logo-pluginarchitecture.png">
      <Pack>True</Pack>
      <PackagePath>
      </PackagePath>
    </EmbeddedResource>
  </ItemGroup>
</Project>