<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <LangVersion>13</LangVersion>
    <AssemblyVersion>11.0.1</AssemblyVersion>
    <FileVersion>11.0.1</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.assert" Version="2.9.3" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AutoVersion\AutoVersion.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>
  <ItemGroup>
    <None Update="SampleCsProj.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TargetCsProj.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <PropertyGroup>
    <LatestAutoVersionSignature>{
   "Name": "Test.csproj",
   "Classes": [
      {
         "Name": "Test.TestExtractingVersionFromCsProjFile",
         "Methods": {
            "TestProjectWithNoVersions": {
               "MethodName": "TestProjectWithNoVersions",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "TestMajorUpdate": {
               "MethodName": "TestMajorUpdate",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSelfSignature",
         "Methods": {
            "IAmInTheSignature": {
               "MethodName": "IAmInTheSignature",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestVersion",
         "Methods": {
            "CanExtractPartsFromVersionString": {
               "MethodName": "CanExtractPartsFromVersionString",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "VerifyIncrementingLogic": {
               "MethodName": "VerifyIncrementingLogic",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "given",
                        "ParameterType": "String",
                        "IsRequired": true
                     },
                     {
                        "ParameterName": "expected",
                        "ParameterType": "String",
                        "IsRequired": true
                     },
                     {
                        "ParameterName": "incrementer",
                        "ParameterType": "VersionType",
                        "IsRequired": true
                     }
                  ]
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestMethodInputParameterOverrideRemoved",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "MethodInputParameterOverrideIsNotChanged": {
               "MethodName": "MethodInputParameterOverrideIsNotChanged",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "MethodInputParameterIsRenamed": {
               "MethodName": "MethodInputParameterIsRenamed",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "MethodInputParameterOverrideTypeChanged": {
               "MethodName": "MethodInputParameterOverrideTypeChanged",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestMethodOverrideAdded",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "MethodOverrideIsNotChanged": {
               "MethodName": "MethodOverrideIsNotChanged",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "MethodOverrideAdded": {
               "MethodName": "MethodOverrideAdded",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestMethodReturnType",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "ReturnTypeIsNotChanged": {
               "MethodName": "ReturnTypeIsNotChanged",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "ReturnTypeIsChanged": {
               "MethodName": "ReturnTypeIsChanged",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestMethodsContinueToExist",
         "Methods": {
            "TestChangeType": {
               "MethodName": "TestChangeType",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "EvaluateMethodStillExists": {
               "MethodName": "EvaluateMethodStillExists",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "EvaluateMethodNoLongerExists": {
               "MethodName": "EvaluateMethodNoLongerExists",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestProjectAdded",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "ProjectsSame": {
               "MethodName": "ProjectsSame",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "ProjectAdded": {
               "MethodName": "ProjectAdded",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestProjectClassAdded",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "ProjectsSame": {
               "MethodName": "ProjectsSame",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "ProjectClassAdded": {
               "MethodName": "ProjectClassAdded",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestProjectClassesContinueToExist",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "ProjectsSame": {
               "MethodName": "ProjectsSame",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "ClassNotFound": {
               "MethodName": "ClassNotFound",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestProjectsContinueToExist",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "ProjectsStillExist": {
               "MethodName": "ProjectsStillExist",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "ProjectsNoLongerExist": {
               "MethodName": "ProjectsNoLongerExist",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestPropertiesContinueToExist",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "PropertiesTheSame": {
               "MethodName": "PropertiesTheSame",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "PropertyRemoved": {
               "MethodName": "PropertyRemoved",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestPropertyEditabilityEnhanced",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "PropertiesTheSame": {
               "MethodName": "PropertiesTheSame",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "PropertyMadeEditable": {
               "MethodName": "PropertyMadeEditable",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestPropertyEditabilityReduced",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "PropertiesTheSame": {
               "MethodName": "PropertiesTheSame",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "PropertyMadeReadOnly": {
               "MethodName": "PropertyMadeReadOnly",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestPropertyReadabilityEnhanced",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "PropertiesTheSame": {
               "MethodName": "PropertiesTheSame",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "PropertyMadeReadable": {
               "MethodName": "PropertyMadeReadable",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestPropertyReadabilityReduced",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "PropertiesTheSame": {
               "MethodName": "PropertiesTheSame",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "PropertyMadeUnReadable": {
               "MethodName": "PropertyMadeUnReadable",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      },
      {
         "Name": "Test.TestSignatureEvaluators.TestPropertyType",
         "Methods": {
            "ChangeTypeIsExpected": {
               "MethodName": "ChangeTypeIsExpected",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "PropertyTypesSame": {
               "MethodName": "PropertyTypesSame",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "PropertyTypesChanged": {
               "MethodName": "PropertyTypesChanged",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      }
   ]
}</LatestAutoVersionSignature>
  </PropertyGroup>
</Project>