<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyVersion>8.0.25</AssemblyVersion>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AutoVersion\AutoVersion.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.assert" Version="2.9.3" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup>
    <LatestAutoVersionSignature>{
   "Name": "IntegrationTest.csproj",
   "Classes": [
      {
         "Name": "IntegrationTest.Class1",
         "Methods": {
            "get_Property1": {
               "MethodName": "get_Property1",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            },
            "set_Property1": {
               "MethodName": "set_Property1",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "value",
                        "ParameterType": "String",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "Method1": {
               "MethodName": "Method1",
               "MethodType": "Void",
               "Overrides": [
                  [
                     {
                        "ParameterName": "param1",
                        "ParameterType": "String",
                        "IsRequired": true
                     },
                     {
                        "ParameterName": "param2",
                        "ParameterType": "Int32",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "GetType": {
               "MethodName": "GetType",
               "MethodType": "Type",
               "Overrides": [
                  []
               ]
            },
            "ToString": {
               "MethodName": "ToString",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            },
            "Equals": {
               "MethodName": "Equals",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "obj",
                        "ParameterType": "Object",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "GetHashCode": {
               "MethodName": "GetHashCode",
               "MethodType": "Int32",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {
            "Property1": {
               "Name": "Property1",
               "Type": "String",
               "IsReadable": true,
               "IsWritable": true
            }
         }
      },
      {
         "Name": "IntegrationTest.Regression",
         "Methods": {
            "TestProgramInvocation": {
               "MethodName": "TestProgramInvocation",
               "MethodType": "Void",
               "Overrides": [
                  []
               ]
            },
            "GetType": {
               "MethodName": "GetType",
               "MethodType": "Type",
               "Overrides": [
                  []
               ]
            },
            "ToString": {
               "MethodName": "ToString",
               "MethodType": "String",
               "Overrides": [
                  []
               ]
            },
            "Equals": {
               "MethodName": "Equals",
               "MethodType": "Boolean",
               "Overrides": [
                  [
                     {
                        "ParameterName": "obj",
                        "ParameterType": "Object",
                        "IsRequired": true
                     }
                  ]
               ]
            },
            "GetHashCode": {
               "MethodName": "GetHashCode",
               "MethodType": "Int32",
               "Overrides": [
                  []
               ]
            }
         },
         "Properties": {}
      }
   ]
}</LatestAutoVersionSignature>
  </PropertyGroup>
</Project>