<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AutoVersion\AutoVersion.csproj" />
    </ItemGroup>


    <UsingTask TaskName="AutoVersion" AssemblyFile="$(OutDir)AutoVersion.dll" />
    <Target Name="RunCustomTask" AfterTargets="PostBuildEvent">
        <AutoVersion ProjectFile="./$(ProjectFileName)" />
    </Target>

    <!--    
    <UsingTask TaskName="AutoVersion" AssemblyFile="$(PkgYamamari_AutoVersion)/lib/net8.0/AutoVersion.dll" />
    <Target Name="IncrementTheVersion" AfterTargets="PostBuildEvent">
        <AutoVersion ProjectFile="./$(ProjectFileName)" />
    </Target>
    -->
</Project>
